### PR TITLE
Feature 22/improve search

### PR DESCRIPTION
**Pull request by PhotoNomad0**
For #22 
Provides all features except search by paragraph.

### CODE REVIEW

**Review by mvahowe — COMMENTED** [review]
The functionality looks good here, but, for search, I think we need a report indexed by chapter/verse, not the entire book text with the matches marked up (because, to display the matches, we'd need to do another search for the marked-up matches). I think we could make that change quite quickly after the collab week.

Also, the per-word markup you demonstrate is exactly what is needed elsewhere (where we didn't manage to do it) so that will be useful too.

Please demo from this branch.

**Comment by PhotoNomad0** [comment]
> The functionality looks good here, but, for search, I think we need a report indexed by chapter/verse, not the entire book text with the matches marked up (because, to display the matches, we'd need to do another search for the marked-up matches). I think we could make that change quite quickly after the collab week.
> 
> Also, the per-word markup you demonstrate is exactly what is needed elsewhere (where we didn't manage to do it) so that will be useful too.
> 
> Please demo from this branch.

@mvahowe I'm not sure what you are saying is a problem. We don't show entire book text, just verses that have a match.  Also it looks like the search results are matching what you suggested as format (copied that into the issue).

**Comment by PhotoNomad0** [comment]
We do have three different displays in the pipeline.  Is that causing confusion?

**Review by mvahowe — APPROVED** [review]
Looking again, this is indeed what we agreed. Sorry for misreading the output earlier. I'll merge this and look forward to the demo, which you should be able to do from main.

**Pull request merged**
